clusterName: talos-auto
talosVersion: v1.10.1 
kubernetesVersion: v1.33.0 
endpoint: https://1.2.3.4:6443
domain: talos-2.local
allowSchedulingOnMasters: true
overrideExtraManifests: true
overridePatches: true

clusterPodNets:
  - 10.244.0.0/16
clusterSvcNets:
  - 10.96.0.0/16

cniConfig:
  name: flannel

patches:
  - |-
    - op: add
      path: /machine/kubelet/extraArgs
      value:
        rotate-server-certificates: "true"
  - |-
    cluster:
      extraManifests:
        - https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
        - https://github.com/volodya261/TalosKub/releases/download/0.01/csi-local-storage.yaml
        - https://github.com/volodya261/TalosKub/releases/download/0.01/victoria.yaml
        - https://github.com/volodya261/TalosKub/releases/download/0.01/grafana.yaml

nodes:
  - hostname: talos-master
    ipAddress: 1.2.3.4
    controlPlane: true
    machineSpec:
      mode: metal
      arch: amd64
    installDisk: /dev/sda
    networkInterfaces:
      - interface: eth0
        dhcp: true
    userVolumes:
    - name: local-storage
      provisioning:
        diskSelector:
          match: disk.transport == "sata"
        maxSize: 50GiB
      filesystem:
        type: ext4 
        wipe: true
